# Generated by Django 3.2.6 on 2021-08-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomType',
        ),
        migrations.AddField(
            model_name='room',
            name='roomType',
            field=models.ManyToManyField(help_text='Select a room type', to='catalog.RoomType'),
        ),
    ]
