# Generated by Django 3.2.6 on 2021-08-26 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210826_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomType',
        ),
        migrations.AddField(
            model_name='room',
            name='roomType',
            field=models.ForeignKey(help_text='Select a room type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.roomtype'),
        ),
    ]
